package server.communication.response;

public enum Responses {
    BAD_REQUEST,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_FAIL,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAIL,
    TOKEN_NOT_FOUND,
    INVALID_USER,
    GAME,
    INVALID_GAME_REQUEST,
    INVALID_GAME_COMMAND,
    USER_LOGOUT_SUCCESS
}
